### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by philips** [skynetservices/skydns1#1]
Nice work on skydns! Glad you found goraft to work well.

What is the license of this project? Guessing it should be MITl like skynet2?

Thanks!

Brandon

**Comment by erikstmartin** [comment]
Brian and I are both the "Do whatever you want with it" types. So yeah, we'll probably go MIT like Skynet. We're open to other licensing options though if it works better for people.

I'll get a license uploaded here shortly, along with some typos I see in the README

**Comment by philips** [comment]
@erikstmartin Cool, MIT sounds good. I always forget to add a LICENSE file so I thought I would let you guys know it was missing.

Cheers,

Brandon
