### ISSUE TITLE
TLS Listener

### ISSUE THREAD

**Issue by densone** [skynetservices/skydns1#18]
Since we are talking about a shred key in another thread, I thought it would be smart ti add a note for adding some encryption to the http side,

**Comment by bketelsen** [comment]
as long as it's optional.  I suspect most will just use firewalls for this security, but a TLS listener would be fine.

**Comment by bketelsen** [comment]
maybe we should bump this one up higher in priority, just keep it optional.

**Comment by densone** [comment]
I actually just made an sni based tis listener. Let me try to find some time next week to make  a PR.   

-Sean

**Comment by bketelsen** [comment]
awesome!
I'm making an etcd service manager so we don't have to depend on zookeeper.

**Comment by miekg** [comment]
Mass closing comments in preparation of moving skydns2 to skydns
