### ISSUE TITLE
skyctl - cli app for skydns

### ISSUE THREAD

**Issue by crosbymichael** [skynetservices/skydns1#47]
If we( I will do this ) to work on a cli app for skydns would you rather the code be in this repo or a separate repository?  It would have commands like:

`skyctl add test1 {}`
`skyctl update test1 10`
`skyctl delete test1`

Any ideas or feedback?

**Comment by bketelsen** [comment]
it makes sense as a subdirectory of this repo - happy to take the PR, it's something on our TODO list.

**Comment by miekg** [comment]
As we already include miekg/dns you can use it to perform dns queries.
