### ISSUE TITLE
Start making binary releases on github

### ISSUE THREAD

**Issue by crosbymichael** [skynetservices/skydns1#50]
Github allow you to tag release and upload binaries for those tags.  It would be nice to have OSX, linux, etc builds on the release page.  I'll also work on having this fully running in docker so it's even easier if you don't mind having a Dockerfile in the repo.

Here is a good example:

https://github.com/coreos/etcd/releases/tag/v0.2.0

**Comment by bketelsen** [comment]
I started on a cross-compile setup at home.  I'll try to get this done.

**Comment by bketelsen** [comment]
docker containers are better :) can we close this?

**Comment by crosbymichael** [comment]
Yep ;)
