### ISSUE TITLE
converting dots

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns1#70]
Right now a Name or Version with dots in it gets converted to a hyphen. From a DNS perspective this is unnecessary, but skydns splits everything on a dot, so changing this breaks skydns quite fundamentally. 

But it is also non obvious that querying for 1.0.1, should be done with 1-0-1. It may be an idea to reject requests with dots in them and only allow version strings like 1-0-1 when registering.

**Comment by erikstmartin** [comment]
It should be converting .'s in the versions to - on Add() is that not the case anymore?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [skydns] converting dots (#70)..." ]

> It should be converting .'s in the versions to - on Add() is that not the case anymore?

It should... If not (anymore), that is a bug that someone (prolly me)
introduced.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
dropped in skydns2.
