### ISSUE TITLE
Let skydns reply to NS queries

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns1#75]
Make NS send replies for NS queries. This would allow clients to discover all the nameservers in the SkyDNS cluster even if they only know of a subset of nameserver ip.

**Comment by miekg** [comment]
The change is trivial, but I'm stuck on the names, we call the master nameserver, master.skydns.local, what would be a good name for the other nameservers? master1, master2? slave1, slave2, or something better.

**Comment by bketelsen** [comment]
"master and member" are better than "master and slave".

**Comment by miekg** [comment]
Ok.

OTOH, we do provide functionality by responding to A queries for master.skydns.local... Also note that we hijack these names and that they cannot be used for hosts registering SRV records. This is btw already a problem (I think).
