### ISSUE TITLE
IRC or other communication channel

### ISSUE THREAD

**Issue by tylerflint** [skynetservices/skydns1#81]
This is a fantastic project. I'd love to be able to discuss possibilities with the authors or other familiar users. Is there already an irc channel or a user group?

Pretty cool stuff.

Thanks

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[skydns] IRC or other communication..." ]

> This is a fantastic project. I'd love to be able to discuss possibilities with the authors or other familiar users. Is there already an irc channel or a user group?

There is https://groups.google.com/forum/#!forum/skynet-dev

I'm subscribed, but it is not very active. Some people might on irc, dunno.

grtz Miek

**Comment by erikstmartin** [comment]
There is a #skynet-dev channel on freenode as well, I haven't been on there in a while, I need to jump back in there

**Comment by miekg** [comment]
Mass closing comments in preparation of moving skydns2 to skydns
