### ISSUE TITLE
Skydns is case sensitive 

### ISSUE THREAD

**Issue by crosbymichael** [skynetservices/skydns1#82]
Queries with difference case fail with skydns.

ping @miekg

**Comment by crosbymichael** [comment]
Any idea of a good place to make this change?

**Comment by erikstmartin** [comment]
Looks like an oversight, when the key to store it is created everything is lowercased https://github.com/skynetservices/skydns/blob/master/registry/registry.go#L432

but when the search is performed it takes the casing as requested. The best i'd recommend making the change is
https://github.com/skynetservices/skydns/blob/master/registry/registry.go#L223

If strings.ToLower(domain) is called at the beginning of the function that should solve the issue you're seeing.

I can make that change here in a few mins if you'd like

**Comment by crosbymichael** [comment]
Thanks for fixing this so quickly.

**Comment by erikstmartin** [comment]
No problem, as soon as I saw the email I knew exactly what it was, just had to wait to be near a computer to fix it :)

**Comment by crosbymichael** [comment]
@erikstmartin it looks like the domain still needs to be checked for case.  `redis.dev.docKer` fails

**Comment by erikstmartin** [comment]
Oh you're right. This logic takes place after the anchor domain has been trimmed off. I'll reopen this and i'll get a fix in for that as well.

**Comment by erikstmartin** [comment]
Should be all set now

**Comment by miekg** [comment]
Lgtm, I'll double check the dns package.

**Comment by bketelsen** [comment]
@miekg feel free to merge when you're happy.
