### ISSUE TITLE
mv skydns2 skydns

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns1#92]
I'm working on the finishing touches (DNSSEC and stats.go) in SkyDNS2 and I feel/think it is ready to be moved to the skydns repository. But it hasn't seen any real live traffic yet. It should be stable (TM).

How do we do the move? Do we _want_ to make this move? How do we tell our users?

**Comment by bketelsen** [comment]
maybe fork off skydns into a "legacy" repository?
then move skydns2 here.  That's my vote.

**Comment by miekg** [comment]
Current skydns will live on in skydns1
New Skydsn2 will live on in skydns.

Closing as I'm about to make this move.
