### ISSUE TITLE
Typo in link

### ISSUE THREAD

**Issue by dminkovsky** [skynetservices/skydns1#96]
The link in the README that points to SkyDNS2:

"This is an heads up that this version of SkyDNS is going to be replaced by SkyDNS2 which is backed by etcd."

points back to this repo. I think you intended it to point to skynetservices/skydns?

**Comment by miekg** [comment]
Ah, yes, haven't updated it when I made the switch. Feel free to change.

**Comment by dminkovsky** [comment]
Cool, thank you.
